export const CREATING_NODE = "CREATING_NODE";
export const CREATED_NODE = "CREATED_NODE";
export const DELETING_NODE = "DELETING_NODE";
export const CREATING_LINK = "CREATING_LINK";
export const DELETING_LINK = "DELETING_LINK";
export const DETAIL_NODE = "DETAIL_NODE";
export const DETAIL_LINK = "DETAIL_LINK";
